{% set name = "elasticsearch" %}
{% set version = "7.8.0" %}

package:
  name: elasticsearch
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/elasticsearch/elasticsearch-{{ version }}.tar.gz
  sha256: e637d8cf4e27e279b5ff8ca8edc0c086f4b5df4bf2b48e2f950b7833aca3a792

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - urllib3 >=1.21.1
    - requests >=2.4.0,<3.0.0
    - certifi

test:
  imports:
    - elasticsearch
    - elasticsearch.client
    - elasticsearch.connection
    - elasticsearch.helpers

about:
  home: https://github.com/elastic/elasticsearch-py
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Python client for Elasticsearch'
  doc_url: https://elasticsearch-py.readthedocs.io
  dev_url: https://github.com/elastic/elasticsearch-py

extra:
  recipe-maintainers:
    - pmlandwehr
