{% set name = "elasticsearch" %}
{% set version = "9.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/elastic/{{ name }}-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 878e8cb1b74a472ff0a8565cd2fdc6987267ace18758ad88acf6481611cff950

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - elastic-transport >=9.4.1,<10
    - python-dateutil
    - typing_extensions
    - sniffio
    - anyio
  run_constrained:
    # async
    - aiohttp >=3,<4
    # requests
    - requests >=2.4.0,!=2.32.2,<3.0.0
    # orjson
    - orjson >=3
    # pyarrow
    - pyarrow >=1
    # vectorstore_mmr
    - numpy >=1
    - simsimd >=3

# E   ModuleNotFoundError: No module named 'test_elasticsearch.test_dsl.test_integration.test_examples.async_examples'
# E   ModuleNotFoundError: No module named 'test_elasticsearch.test_dsl.test_integration.test_examples.examples'
{% set ignore_tests = " --ignore=test_elasticsearch/test_dsl/test_integration/test_examples/_async" %}  # [win]
{% set ignore_tests = ignore_tests + " --ignore=test_elasticsearch/test_dsl/test_integration/test_examples/_sync" %}  # [win]
{% set ignore_tests = ignore_tests + " --ignore=test_elasticsearch/test_async/test_server" %}  # [win]
{% set ignore_tests = ignore_tests + " --ignore=test_elasticsearch/test_client/test_overrides.py" %}  # [win]
test:
  source_files:
    - test_elasticsearch
    # By some reason the tests fail to import these modules on Windows on CI
    - test_elasticsearch/utils.py  # [win]
    - test_elasticsearch/test_dsl/test_integration/_async  # [win]
    - test_elasticsearch/test_dsl/test_integration/_sync  # [win]
    - test_elasticsearch/test_dsl/test_integration/__init__.py  # [win]
    - test_elasticsearch/test_dsl/test_integration/test_data.py  # [win]
  imports:
    - elasticsearch
    - elasticsearch.client
    - elasticsearch.compat
  requires:
    - pip
    - pytest
    - pytz
    - requests
    - pydantic
    - pyyaml
    - orjson
    - trio
    - pytest-asyncio
    - aiohttp
    - numpy
  commands:
    - pip check
    - dir /s test_elasticsearch\utils.py  # [win]
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv test_elasticsearch  # [not win]
    - python -m pytest --import-mode=importlib -vv {{ ignore_tests }} test_elasticsearch  # [win]

about:
  home: https://github.com/elastic/elasticsearch-py
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Official low-level client for Elasticsearch. Its goal is to provide common ground for all Elasticsearch-related code in Python; because of this it tries to be opinion-free and very extendable.
  summary: Python client for Elasticsearch
  doc_url: https://elasticsearch-py.readthedocs.io
  dev_url: https://github.com/elastic/elasticsearch-py

extra:
  recipe-maintainers:
    - ahlaw
    - sethmlarson
