{% set name = "elasticsearch" %}
{% set version = "7.0.4" %}

package:
  name: elasticsearch
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/elasticsearch/elasticsearch-{{ version }}.tar.gz
  sha256: d9eda8d9696f55d7d394ade625a262985d7af762c0b9305b73d421dace41c4e7

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - urllib3 >=1.21.1
    - requests >=2.4.0,<3.0.0

test:
  imports:
    - elasticsearch
    - elasticsearch.client
    - elasticsearch.connection
    - elasticsearch.helpers

about:
  home: https://github.com/elastic/elasticsearch-py
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Python client for Elasticsearch'
  doc_url: https://elasticsearch-py.readthedocs.io
  dev_url: https://github.com/elastic/elasticsearch-py

extra:
  recipe-maintainers:
    - pmlandwehr
