{% set name = "elasticsearch" %}
{% set version = "9.2.0" %}

package:
  name: elasticsearch
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/elasticsearch/elasticsearch-{{ version }}.tar.gz
  sha256: 99656baa34b10130402b6c38429feddf7aee1c3247566e8f95f0d0267fe9f9ab

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - urllib3 >=1.21.1,<2
    - requests >=2.4.0,<3.0.0
    - certifi
    - aiohttp >=3,<4
    - elastic-transport >=9.2.0,<10
    - python-dateutil
    - typing_extensions
    - sniffio
    - anyio
  run_constrained:
    - orjson >=3
    - pyarrow >=1
    - numpy >=1
    - simsimd >=3
    - aiohttp >=3,<4
    - requests >=2.4.0,!=2.32.2,<3.0.0

test:
  imports:
    - elasticsearch
    - elasticsearch.client
    - elasticsearch.compat
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/elastic/elasticsearch-py
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Official low-level client for Elasticsearch. Its goal is to provide common ground for all Elasticsearch-related code in Python; because of this it tries to be opinion-free and very extendable.
  summary: Python client for Elasticsearch
  doc_url: https://elasticsearch-py.readthedocs.io
  dev_url: https://github.com/elastic/elasticsearch-py

extra:
  recipe-maintainers:
    - ahlaw
    - sethmlarson
