{% set name = "elasticsearch" %}
{% set version = "7.13.0" %}

package:
  name: elasticsearch
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/elasticsearch/elasticsearch-{{ version }}.tar.gz
  sha256: da3de0451c61e9357cec2f8bf32d8aea65974e5717b5deef53718392cf4c2985

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel

  run:
    - python >=3.6
    - urllib3 >=1.21.1,<2
    - requests >=2.4.0,<3.0.0
    - certifi
    - aiohttp >=3,<4

test:
  imports:
    - elasticsearch
    - elasticsearch.client
    - elasticsearch.connection
    - elasticsearch.helpers

about:
  home: https://github.com/elastic/elasticsearch-py
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Python client for Elasticsearch
  doc_url: https://elasticsearch-py.readthedocs.io
  dev_url: https://github.com/elastic/elasticsearch-py

extra:
  recipe-maintainers:
    - ahlaw
    - sethmlarson
