{% set name = "elasticsearch" %}
{% set version = "9.4.1" %}
{% set ignore_tests = "" %}
{% set ignore_tests = ignore_tests + " --ignore=test_elasticsearch/test_dsl/test_integration/test_examples/_async" %}  # [win]
{% set ignore_tests = ignore_tests + " --ignore=test_elasticsearch/test_dsl/test_integration/test_examples/_sync" %}  # [win]

# E   ModuleNotFoundError: No module named 'test_elasticsearch.test_dsl.test_integration.test_examples.async_examples'
# E   ModuleNotFoundError: No module named 'test_elasticsearch.test_dsl.test_integration.test_examples.examples'
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/elastic/{{ name }}-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c9aac2d519a919ba03aaf7eed15ecf1f2cd468f6a6939d6f8c88ded54dde4a47

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - elastic-transport >=9.4.1,<10
    - python-dateutil
    - typing_extensions
    - sniffio
    - anyio
  run_constrained:
    - aiohttp >=3,<4
    - requests >=2.4.0,!=2.32.2,<3.0.0
    - orjson >=3
    - pyarrow >=1
    - numpy >=1
    - simsimd >=3

test:
  source_files:
    - test_elasticsearch
  imports:
    - elasticsearch
    - elasticsearch.client
    - elasticsearch.compat
  requires:
    - pip
    - pytest
    - pytz
    - requests
    - pydantic
    - pyyaml
    - orjson
    - trio
    - pytest-asyncio
    - aiohttp
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v {{ ignore_tests }} test_elasticsearch

about:
  home: https://github.com/elastic/elasticsearch-py
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Official low-level client for Elasticsearch. Its goal is to provide common ground for all Elasticsearch-related code in Python; because of this it tries to be opinion-free and very extendable.
  summary: Python client for Elasticsearch
  doc_url: https://elasticsearch-py.readthedocs.io
  dev_url: https://github.com/elastic/elasticsearch-py

extra:
  recipe-maintainers:
    - ahlaw
    - sethmlarson
