travis:
  secure:
    BINSTAR_TOKEN: Z3CMUKh0PEcrBiAnYcon+BWmXWPGbBxud6Nl3DHbDB+f6TgX1yGUvXj4r8sZuU5T57/P1JiE0JlOHsPnHITE3XU8eejmNMWyvTofZfzZtR8vO4W81umW2Hp0ItVQPwggYXeAu24lOcj85irWos/harf7ftf4iFei+Ua8K0tylNikHiRQszsnoE1ERfQ9L/TBt5ULQVZ1miWOT9midUZT9WdjzgXSa/ZXj7pprFcQnEyAkZviYm3QYLJqwTcRYL1iEnSgXng08yHTwwa35Vcpxh8Or+SRQsCYMbsHJzKhNCmgY+SZ3dL1ziGJNsB3+bHa5WjA7vt+nneeqUACfwSntAgbUCxn80Mu4HZcrlJ9nKchqJrs18jHJWhwmdlvdPg+PVO1aSpVzIM6wvjbjRScI+i7Lg3r+ZcfsLgY2rQoME+3rN9Tu5iiY2nVmQ49JZon71b7LAdDboBe9Jd1Us4/3rlFZDC6/E/AKddzZlNPXAteBvRQQTkBLO8l1MkyKzut3nqdFy/so7ILfgHqZpU73jqhVHdk/LLCRfZSGATmSdFND0yaywisbC4eeMHT2kHiw0BNHvdvHsT08AeCegLHHJqdB1TxkyNYdZ3DiIQ293ob3/w+PCSY55zdundnVqih/7AOeLUJc5Fd2vX3JnlbcBWuFdCyCgpTE9tgSZOAwOg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
